### ISSUE TITLE
Error "Cannot find /opt/atlassian/jira/bin/setclasspath.sh"

### ISSUE THREAD

**Issue by lospejos** [babim/docker-atlassian-jira-software#1]
I receive error to start Jira using this image.
Log:

```
$ docker run -it --rm --publish 8080:8080 babim/jira-software:latest
Unable to find image 'babim/jira-software:latest' locally
latest: Pulling from babim/jira-software
a0d0a0d46f8b: Already exists
fc2f4f143a77: Pull complete
e07ed5dcef9c: Pull complete
de8e03af5fbd: Pull complete
0b2ae5ee8dbf: Pull complete
c174ff12256d: Pull complete
Digest: sha256:c5e3b6c1010ed09b11fd7b63c3306960b706f6fdfcf642e4dc37800eb3b3efae
Status: Downloaded newer image for babim/jira-software:latest
Check OS
Options run value are empty
Options run value are empty
Options run value are empty
Options run value are empty
Options run value are empty
Options run value are empty
ln: /etc/localtime: File exists
executing as current user
Cannot find /opt/atlassian/jira/bin/setclasspath.sh
This file is needed to run this program
```

Please assist. Thanks.

**Comment by lospejos** [comment]
I ran docker container with overridden entry point like this:
```
docker run -it --rm --publish 8080:8080 --entrypoint /bin/ash babim/jira-software:latest
```
Being inside running container, I successfully found the file `/opt/atlassian/jira/bin/setclasspath.sh` which is not found in above-mentioned error:
```
/var/atlassian/jira $ ls -la /opt/atlassian/jira/bin/ | grep setclass
-rw-r--r--    1 root     root          3460 Mar 30  2021 setclasspath.bat
-rwxr-xr-x    1 root     root          3708 Mar 30  2021 setclasspath.sh
```

**Comment by babim** [comment]
└─# docker run -it --rm --publish 8080:8080 babim/jira-software:latest
Unable to find image 'babim/jira-software:latest' locally
latest: Pulling from babim/jira-software
a0d0a0d46f8b: Pull complete 
b0826f593dcd: Pull complete 
a76bb6a8bc61: Pull complete 
f86e3a9e3b96: Pull complete 
5fbee82c071b: Pull complete 
970a0fe09887: Pull complete 
Digest: sha256:57bbb118b7c5120f42e1bf0631a22d96d53490c98de994b3f0ac8b2fe1ca7f38
Status: Downloaded newer image for babim/jira-software:latest
Check OS
Options run value are empty
Options run value are empty
Options run value are empty
Options run value are empty
Options run value are empty
Options run value are empty
ln: /etc/localtime: File exists
executing as current user

                  `sMMMMMMMMMMMMMM+
                     MMMMMMMMMMMMMM
                     :sdMMMMMMMMMMM
                             MMMMMM
          `sMMMMMMMMMMMMMM+  MMMMMM
             MMMMMMMMMMMMMM  +MMMMM
              :sMMMMMMMMMMM   MMMMM
                     MMMMMM    `UOJ
   `sMMMMMMMMMMMMM+  MMMMMM
     MMMMMMMMMMMMMM  +MMMMM
      :sdMMMMMMMMMM   MMMMM
             MMMMMM    `UOJ
             MMMMMM
             +MMMMM
              MMMMM
               `UOJ

      Atlassian Jira
      Version : 8.21.0
                  

If you encounter issues starting or stopping Jira, please see the Troubleshooting guide at https://docs.atlassian.com/jira/jadm-docs-0821/Troubleshooting+installation

Using JIRA_HOME:       /var/atlassian/jira

Server startup logs are located in /opt/atlassian/jira/logs/catalina.out
Using CATALINA_BASE:   /opt/atlassian/jira
Using CATALINA_HOME:   /opt/atlassian/jira
Using CATALINA_TMPDIR: /opt/atlassian/jira/temp
Using JRE_HOME:        /opt/java/openjdk
Using CLASSPATH:       /opt/atlassian/jira/bin/bootstrap.jar:/opt/atlassian/jira/bin/tomcat-juli.jar
Using CATALINA_OPTS:   
Using CATALINA_PID:    /opt/atlassian/jira/work/catalina.pid
07-Mar-2022 00:35:47.365 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version name:   Apache Tomcat/8.5.72
